apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: druid-brokers
spec:
  serviceName: druid-brokers
  replicas: 1
  selector:
    matchLabels:
      app: druid
      nodeType: broker
  template:
    metadata:
      labels:
        app: druid
        nodeType: broker
      annotations:
        druid.k8s.enablePatching: "true"
    spec:
      serviceAccountName: druid-cluster
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: druid-brokers
          image: apache/druid
          command: ["/druid.sh", "broker"]
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: druid_host
              value: "$(POD_IP)"
          ports:
            - name: druid-port
              containerPort: 8082
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /status/health
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /status/health
              port: 8082
            initialDelaySeconds: 120
            periodSeconds: 15
            timeoutSeconds: 30
            failureThreshold: 20
          readinessProbe:
            httpGet:
              path: /status/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 30
            failureThreshold: 10
          volumeMounts:
            - name: common-config
              mountPath: /opt/druid/conf/druid/cluster/_common
            - name: node-config
              mountPath: /opt/druid/conf/druid/cluster/query/broker
            - name: data
              mountPath: /opt/druid/var
      volumes:
        - name: common-config
          configMap:
            name: druid-common-config
        - name: node-config
          configMap:
            name: druid-broker-config
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: druid-brokers
spec:
  selector:
    app: druid
    nodeType: broker
  ports:
    - port: 8082
      targetPort: 8082
