apiVersion: v1
kind: ConfigMap
metadata:
  name: druid-coordinator-config
data:
  runtime.properties: |
    druid.service=druid/coordinator
    druid.plaintextPort=8081
    druid.coordinator.startDelay=PT30S
    druid.coordinator.period=PT30S
    druid.coordinator.asOverlord.enabled=false
    druid.coordinator.loadqueuepeon.type=http
    druid.server.http.numThreads=60
  jvm.config: |-
    -server
    -Duser.timezone=UTC
    -Dfile.encoding=UTF-8
    -XX:+ExitOnOutOfMemoryError
    -XX:+UseG1GC
    -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager
    -Djava.io.tmpdir=var/tmp
    -Xms256m
    -Xmx256m
    -XX:MaxDirectMemorySize=256m
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="WARN">
      <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
          <PatternLayout pattern="%d{ISO8601} %p [%t] %c - %m%n"/>
        </Console>
      </Appenders>
      <Loggers>
        <Root level="info">
          <AppenderRef ref="Console"/>
        </Root>
      </Loggers>
    </Configuration>
