apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - rbac.yaml
  - postgres-secret.yaml
  - postgres.yaml
  - common-configmap.yaml
  - coordinator-configmap.yaml
  - coordinator.yaml
  - overlord-configmap.yaml
  - overlord.yaml
  - broker-configmap.yaml
  - broker.yaml
  - historical-configmap.yaml
  - historical.yaml
  - indexer-configmap.yaml
  - indexer.yaml
  - router-configmap.yaml
  - router.yaml
